apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: adaoex/gitopsfc
  newTag: 982244a851ebbbaca859a81496508c8d872907e8
