apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: adaoex/gitopsfc
  newTag: 001b983075016abaa6de4b7c45aad750224aacc6
